name: Run python tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies with poetry
        run: poetry install
      - name: Install pre-commit
        run: poetry run pip install pre-commit
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
      - name: Run tests
        run: poetry run pytest -vv --strict --showlocals
